export const BRIEFING_FILTERS = [
  { key: "all", label: "전체" },
  { key: "film", label: "필름" },
  { key: "wallpaper", label: "도배" },
  { key: "tile", label: "타일" },
  { key: "electric", label: "전기" },
  { key: "facility", label: "설비" },
];

export const BRIEFING_ITEMS = [
  {
    id: "briefing-1",
    craft: "electric",
    icon: "🚨",
    category: "긴급 수요",
    title: "세종 전기 야간작업 증가중",
    summary: "야간 단가 평균 +3만 상승 흐름입니다.",
    region: "세종",
    averagePay: "19~21만",
    trend: "최근 2주 야간 현장 요청 18% 증가",
    updatedAt: "방금 전",
    flow: "관공서·상가 점검 공정이 저녁 시간대로 이동하면서 야간 전기 투입 요청이 꾸준히 늘고 있습니다.",
  },
  {
    id: "briefing-2",
    craft: "film",
    icon: "📈",
    category: "단가 흐름",
    title: "청주 필름 기공 단가 상승 예상",
    summary: "최근 2주 현장 요청 기준 평균 단가가 상승중입니다.",
    region: "청주",
    averagePay: "16~18만",
    trend: "전주 대비 평균 +1.2만",
    updatedAt: "12분 전",
    flow: "상가 리뉴얼 물량이 몰리면서 기공급 필름 단가가 다음달에도 추가 상승할 가능성이 있습니다.",
  },
  {
    id: "briefing-3",
    craft: "film",
    icon: "📦",
    category: "자재 시세",
    title: "LX 필름 일부 품목 가격 인상 예정",
    summary: "필름 자재 가격이 다음달 일부 인상될 가능성이 있습니다.",
    region: "전국",
    averagePay: "자재비 +2~4%",
    trend: "다음달 초 반영 가능성",
    updatedAt: "25분 전",
    flow: "무광 계열 일부 품목 공급가 조정이 예정돼 있어 현장 견적에 자재비 반영 여지가 커지고 있습니다.",
  },
  {
    id: "briefing-4",
    craft: "film",
    icon: "🔥",
    category: "작업 많은 지역",
    title: "대전 서구 긴급헬프 증가",
    summary: "근처 단기 보조 요청이 빠르게 늘고 있습니다.",
    region: "대전 서구",
    averagePay: "헬프 7~9만",
    trend: "오후 반일 요청 집중",
    updatedAt: "34분 전",
    flow: "둔산·월평 상권 리뉴얼 일정이 겹치며 오후 즉시투입형 헬프 요청이 빠르게 늘어나는 흐름입니다.",
  },
  {
    id: "briefing-5",
    craft: "film",
    icon: "🛠",
    category: "오늘 현장 분위기",
    title: "대전 필름 현장 요청 안정적 유지",
    summary: "현재 평균 단가는 15~17만 수준입니다.",
    region: "대전",
    averagePay: "15~17만",
    trend: "보합 유지",
    updatedAt: "1시간 전",
    flow: "이번 주 대전권 필름 현장 요청은 긴급 변동 없이 안정적으로 유지되고 있어 평균 단가도 큰 변화 없이 보합세입니다.",
  },
  {
    id: "briefing-6",
    craft: "wallpaper",
    icon: "👷",
    category: "인력 수급",
    title: "도배 조공 인력 부족",
    summary: "준공 물량 증가로 조공 수급이 빠듯해지고 있습니다.",
    region: "대전·세종",
    averagePay: "조공 12~14만",
    trend: "오전 배치 수요 증가",
    updatedAt: "1시간 전",
    flow: "주간 준공 물량이 몰리면서 도배 조공 수급이 타이트해져 사전 섭외가 필요한 분위기입니다.",
  },
  {
    id: "briefing-7",
    craft: "tile",
    icon: "📊",
    category: "단기 흐름",
    title: "타일 준기공 반일 요청 증가",
    summary: "오전 마감 보조 중심으로 반일 일정이 늘고 있습니다.",
    region: "세종·청주",
    averagePay: "반일 9~11만",
    trend: "반일 요청 비중 22% 증가",
    updatedAt: "2시간 전",
    flow: "입주 전 마감 일정이 앞당겨지면서 타일 준기공 반일 보조 수요가 눈에 띄게 증가하고 있습니다.",
  },
  {
    id: "briefing-8",
    craft: "facility",
    icon: "🔧",
    category: "설비 동향",
    title: "신축 설비 배관 단가 강보합",
    summary: "대전 유성권 신축 현장 중심으로 단가가 견조합니다.",
    region: "대전 유성구",
    averagePay: "17~19만",
    trend: "강보합",
    updatedAt: "2시간 전",
    flow: "신축 배관 일정이 꾸준히 이어지면서 설비 준기공 이상 단가가 안정적으로 유지되고 있습니다.",
  },
];
