/**
 * Canonical mock job seed (jobModel migrateJob).
 * Core fields: id, title, address, date, participants, briefing, alerts (+ domain extras).
 * 지도 마커·목록 테스트용 시드 (대전·세종 분산, id 1~32).
 */
export const initialJobs = [
  {
    "id": 1,
    "title": "둔산동 상가 필름 시공",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "film",
    "ownerUserId": 902,
    "ownerName": "이소장",
    "lat": 36.356,
    "lng": 127.378,
    "pay": "140,000원",
    "status": "recruiting",
    "isUrgent": true,
    "workType": "fullDay",
    "workTime": "08:30~17:00",
    "distanceKm": 0.9,
    "address": "대전 서구 둔산동",
    "memo": "당일지급",
    "parkingNote": "지하주차장 B2",
    "accessPassword": "1234#",
    "requiredItems": "사다리 필요",
    "mealNote": "점심 제공",
    "specialNote": "오전 집결 후 바로 투입",
    "materialNote": "LX 베니프 화이트 사용",
    "attendanceCount": 12,
    "activeWorkersCount": 4,
    "shortageCount": 1,
    "workerStage": "arrived",
    "settlementStatus": "unpaid",
    "likeCount": 24,
    "listImage": "https://picsum.photos/seed/ildang-site-1/112/112",
    "date": "2026-05-21",
    "addressDetail": "대전 서구 둔산남로 92",
    "participants": [
      {
        "id": "a-1-me",
        "applicantUserId": 1,
        "name": "김OO",
        "role": "기공",
        "experience": 24,
        "noShow": 0,
        "status": "confirmed"
      },
      {
        "id": "a-1-2",
        "name": "이영희",
        "role": "준기공",
        "experience": 18,
        "noShow": 0,
        "status": "applied"
      }
    ],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 2,
    "title": "노은동 아파트 도장 마감",
    "siteKind": "아파트",
    "beginnerOk": true,
    "trade": "기공",
    "craft": "paint",
    "lat": 36.341,
    "lng": 127.39,
    "pay": "150,000원",
    "status": "recruiting",
    "isUrgent": false,
    "workType": "morning",
    "workTime": "07:30~12:00",
    "distanceKm": 2.4,
    "address": "대전 유성구 노은동",
    "memo": "당일지급",
    "closingSoon": true,
    "attendanceCount": 6,
    "activeWorkersCount": 2,
    "shortageCount": 1,
    "workerStage": "departed",
    "likeCount": 8,
    "listImage": "https://picsum.photos/seed/ildang-site-2/112/112",
    "ownerUserId": 1,
    "date": "2026-05-14",
    "addressDetail": "대전 유성구 노은동로 45 현대아파트 상가 2층",
    "participants": [
      {
        "id": "a-2-1",
        "name": "박민수",
        "role": "기공",
        "experience": 32,
        "noShow": 0,
        "status": "confirmed"
      }
    ],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 3,
    "title": "용운동 현장 타일 줄눈·보조",
    "siteKind": "아파트",
    "beginnerOk": true,
    "longTerm": true,
    "trade": "조공",
    "craft": "tile",
    "lat": 36.328,
    "lng": 127.43,
    "pay": "200,000원",
    "status": "recruiting",
    "isUrgent": false,
    "workType": "afternoon",
    "workTime": "13:00~18:00",
    "distanceKm": 3.1,
    "address": "대전 동구 용운동",
    "likeCount": 41,
    "attendanceCount": 5,
    "activeWorkersCount": 0,
    "shortageCount": 2,
    "listImage": "https://picsum.photos/seed/ildang-site-3/112/112",
    "date": "2026-05-22",
    "addressDetail": "대전 동구 용운로 88 용운2차아파트 305동",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 4,
    "title": "은행동 오피스텔 도배 감리",
    "siteKind": "오피스텔",
    "trade": "오야지",
    "craft": "wallpaper",
    "lat": 36.365,
    "lng": 127.395,
    "pay": "180,000원",
    "status": "recruiting",
    "isUrgent": false,
    "isPremium": true,
    "workType": "shortHelp",
    "workTime": "09:00~14:00",
    "distanceKm": 0.8,
    "address": "대전 중구 은행동",
    "payTerms": "당일지급",
    "attendanceCount": 4,
    "activeWorkersCount": 0,
    "settlementStatus": "settled",
    "liveHelp": true,
    "helpTime": "오후 2~5시",
    "helpTitle": "도배 헬프",
    "helpDescription": "2~3시간 보조 가능하신 분",
    "helpDurationMinutes": 150,
    "helpExpiresAt": "2026-05-13T16:10:00+09:00",
    "helpAtmosphere": "잔손 정리와 마감 보조 위주라 손 빠른 기사님이 바로 필요합니다.",
    "likeCount": 15,
    "listImage": "https://picsum.photos/seed/ildang-site-4/112/112",
    "date": "2026-05-20",
    "addressDetail": "대전 중구 중앙로 101 오피스텔 7층",
    "participants": [
      {
        "id": "a-4-1",
        "name": "한상우",
        "role": "기공",
        "experience": 40,
        "noShow": 0,
        "status": "confirmed"
      }
    ],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 5,
    "title": "탄방동 상가 전기 배선 보강",
    "siteKind": "상가",
    "longTerm": true,
    "trade": "기공",
    "craft": "electric",
    "lat": 36.3475,
    "lng": 127.382,
    "pay": "220,000원",
    "status": "recruiting",
    "isUrgent": true,
    "workType": "fullDay",
    "workTime": "08:00~18:00",
    "distanceKm": 1.9,
    "address": "대전 서구 탄방동",
    "description": "익일 지급 협의",
    "parkingNote": "건물 뒤 주차 가능",
    "accessPassword": "A-204",
    "requiredItems": "절연장갑, 드라이버 준비",
    "mealNote": "점심 제공",
    "specialNote": "오후 1시 이후 소음 주의",
    "materialNote": "전선 마감 자재 현장 지급",
    "attendanceCount": 9,
    "activeWorkersCount": 3,
    "shortageCount": 1,
    "likeCount": 56,
    "listImage": "https://picsum.photos/seed/ildang-site-5/112/112",
    "date": "2026-05-21",
    "addressDetail": "대전 서구 문정로 77 상가 3층",
    "participants": [
      {
        "id": "a-5-me",
        "applicantUserId": 1,
        "name": "김OO",
        "role": "기공",
        "experience": 28,
        "noShow": 0,
        "status": "confirmed"
      }
    ],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 6,
    "title": "관저동 신축 설비 배관",
    "siteKind": "신축",
    "longTerm": true,
    "trade": "준기공",
    "craft": "facility",
    "lat": 36.361,
    "lng": 127.412,
    "pay": "190,000원",
    "status": "recruiting",
    "isUrgent": false,
    "workType": "fullDay",
    "workTime": "07:00~16:00",
    "distanceKm": 4.2,
    "address": "대전 대덕구 법동",
    "likeCount": 12,
    "listImage": "https://picsum.photos/seed/ildang-site-6/112/112",
    "date": "2026-05-23",
    "addressDetail": "대전 대덕구 법동 120 신축 현장",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 7,
    "title": "봉명동 학원 도배 준공 정리",
    "siteKind": "학원",
    "beginnerOk": true,
    "trade": "준기공",
    "craft": "wallpaper",
    "lat": 36.351,
    "lng": 127.402,
    "pay": "135,000원",
    "status": "recruiting",
    "isUrgent": false,
    "workType": "morning",
    "workTime": "08:30~13:00",
    "distanceKm": 2,
    "address": "대전 유성구 봉명동",
    "likeCount": 33,
    "listImage": "https://picsum.photos/seed/ildang-site-7/112/112",
    "date": "2026-05-18",
    "addressDetail": "대전 유성구 대학로 88 3층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 8,
    "title": "대흥동 카페 필름 단기",
    "siteKind": "카페",
    "trade": "조공",
    "craft": "film",
    "lat": 36.326,
    "lng": 127.371,
    "pay": "120,000원",
    "status": "recruiting",
    "isUrgent": true,
    "workType": "afternoon",
    "workTime": "12:00~17:00",
    "distanceKm": 2.8,
    "address": "대전 중구 대흥동",
    "liveHelp": true,
    "helpTime": "오후 1시~5시",
    "helpTitle": "필름 보조 급구",
    "helpDescription": "2~3시간 보조 가능하신분",
    "helpDurationMinutes": 120,
    "helpExpiresAt": "2026-05-13T13:30:00+09:00",
    "helpAtmosphere": "점심 이후 바로 투입해야 해서 근처 기사님 우선으로 찾고 있습니다.",
    "likeCount": 19,
    "listImage": "https://picsum.photos/seed/ildang-site-8/112/112",
    "date": "2026-05-20",
    "addressDetail": "대전 중구 중앙로 12 카페",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 9,
    "title": "탄방동 상가 필름 보조 급구",
    "siteKind": "상가",
    "trade": "조공",
    "craft": "film",
    "lat": 36.3496,
    "lng": 127.3852,
    "pay": "80,000원",
    "status": "recruiting",
    "isUrgent": true,
    "liveHelp": true,
    "workType": "shortHelp",
    "workTime": "13:00~17:00",
    "helpTime": "오후 1시~5시",
    "helpTitle": "필름 보조 급구",
    "helpPay": "8만원",
    "helpDescription": "2~3시간 보조 가능하신분",
    "parkingNote": "지하 1층 가능",
    "accessPassword": "2580#",
    "requiredItems": "사다리 필요",
    "mealNote": "간단 식사 제공",
    "specialNote": "카페 영업 전 마감 우선",
    "materialNote": "LX 필름 화이트 계열 사용",
    "helpDurationMinutes": 240,
    "helpExpiresAt": "2026-12-31T18:00:00+09:00",
    "helpAtmosphere": "점심 직후 마감 공정이 몰려 있어 손 빠른 보조 한 분이 바로 필요합니다.",
    "distanceKm": 0.7,
    "address": "대전 서구 탄방동",
    "payTerms": "당일지급",
    "attendanceCount": 7,
    "activeWorkersCount": 5,
    "shortageCount": 1,
    "workerStage": "arrived",
    "likeCount": 37,
    "listImage": "https://picsum.photos/seed/ildang-site-9/112/112",
    "date": "2026-05-20",
    "addressDetail": "대전 서구 둔산남로 92 상가 2층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 10,
    "title": "둔산동 관공서 전기 헬프",
    "siteKind": "관공서",
    "trade": "준기공",
    "craft": "electric",
    "lat": 36.3518,
    "lng": 127.3811,
    "pay": "90,000원",
    "status": "recruiting",
    "isUrgent": true,
    "liveHelp": true,
    "workType": "shortHelp",
    "workTime": "15:00~18:30",
    "helpTime": "오후 3시~6시 30분",
    "helpTitle": "전기 배선 헬프",
    "helpDescription": "배선 정리와 공구 전달 위주입니다.",
    "parkingNote": "청사 뒤편 주차 가능",
    "accessPassword": "E-7788",
    "requiredItems": "검전기, 절연장갑 준비",
    "mealNote": "식사 미제공",
    "specialNote": "출입증 확인 필요",
    "materialNote": "배선 마감 자재 현장 준비",
    "helpDurationMinutes": 90,
    "helpExpiresAt": "2026-05-13T15:50:00+09:00",
    "helpAtmosphere": "마감 점검 전 배선 정리가 몰려 있어 짧게 같이 움직일 분을 찾고 있습니다.",
    "distanceKm": 1.6,
    "address": "대전 서구 둔산동",
    "payTerms": "당일지급",
    "attendanceCount": 6,
    "activeWorkersCount": 4,
    "shortageCount": 1,
    "likeCount": 18,
    "listImage": "https://picsum.photos/seed/ildang-site-10/112/112",
    "date": "2026-05-21",
    "addressDetail": "대전 서구 둔산중로 55 청사 별관",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 11,
    "title": "봉명동 오피스텔 도배 헬프",
    "siteKind": "오피스텔",
    "trade": "조공",
    "craft": "wallpaper",
    "lat": 36.3534,
    "lng": 127.4014,
    "pay": "70,000원",
    "status": "recruiting",
    "isUrgent": true,
    "liveHelp": true,
    "workType": "shortHelp",
    "workTime": "14:00~17:00",
    "helpTime": "오후 2시~5시",
    "helpTitle": "도배 마감 헬프",
    "helpPay": "7만원",
    "helpDescription": "마감 정리와 자재 이동 보조입니다.",
    "helpDurationMinutes": 180,
    "helpExpiresAt": "2026-12-31T17:30:00+09:00",
    "helpAtmosphere": "입주 전 마감이 밀려 있어 근처에서 바로 올 수 있는 분이 필요합니다.",
    "distanceKm": 2.1,
    "address": "대전 유성구 봉명동",
    "payTerms": "당일지급",
    "attendanceCount": 5,
    "activeWorkersCount": 3,
    "shortageCount": 1,
    "likeCount": 21,
    "listImage": "https://picsum.photos/seed/ildang-site-11/112/112",
    "date": "2026-05-22",
    "addressDetail": "대전 유성구 계룡로 114 오피스텔 5층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 14,
    "title": "둔산남로 상가 철거 잔업",
    "siteKind": "상가",
    "trade": "조공",
    "craft": "facility",
    "lat": 36.3554,
    "lng": 127.3778,
    "pay": "90,000원",
    "status": "recruiting",
    "isUrgent": true,
    "liveHelp": true,
    "workType": "shortHelp",
    "workTime": "14:00~17:00",
    "helpTime": "3시간 (오후 2~5시)",
    "helpTitle": "철거 잔업 3시간",
    "helpPay": "9만원",
    "helpDescription": "폐자재 반출·현장 정리 보조",
    "helpDurationMinutes": 200,
    "helpExpiresAt": "2026-12-31T17:00:00+09:00",
    "helpAtmosphere": "소음 구간이라 인원만 빠르게 맞추면 바로 마감 가능합니다.",
    "distanceKm": 1,
    "address": "대전 서구 둔산동",
    "payTerms": "당일지급",
    "attendanceCount": 4,
    "activeWorkersCount": 2,
    "shortageCount": 1,
    "likeCount": 6,
    "listImage": "https://picsum.photos/seed/ildang-site-14/112/112",
    "date": "2026-05-20",
    "addressDetail": "대전 서구 둔산남로 92 상가 지하",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 12,
    "title": "용문동 타일 컷팅 긴급헬프",
    "siteKind": "상가",
    "trade": "준기공",
    "craft": "tile",
    "lat": 36.3389,
    "lng": 127.3927,
    "pay": "85,000원",
    "status": "recruiting",
    "isUrgent": true,
    "liveHelp": true,
    "workType": "shortHelp",
    "workTime": "13:00~16:00",
    "helpTime": "오후 1시~4시",
    "helpTitle": "타일 컷팅 보조",
    "helpDescription": "타일 운반과 컷팅 보조 위주입니다.",
    "helpDurationMinutes": 30,
    "helpExpiresAt": "2026-05-13T12:50:00+09:00",
    "helpAtmosphere": "필요 인원을 이미 확보해서 자동 마감된 상태입니다.",
    "distanceKm": 0.9,
    "address": "대전 서구 용문동",
    "payTerms": "당일지급",
    "attendanceCount": 4,
    "activeWorkersCount": 0,
    "shortageCount": 0,
    "settlementStatus": "unpaid",
    "likeCount": 9,
    "listImage": "https://picsum.photos/seed/ildang-site-12/112/112",
    "date": "2026-05-25",
    "addressDetail": "대전 서구 계룡로 615 상가 1층",
    "participants": [
      {
        "id": "a-12-1",
        "name": "정민호",
        "role": "준기공",
        "experience": 14,
        "noShow": 0,
        "status": "confirmed"
      }
    ],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 13,
    "title": "세종 나성동 상가 전기 야간",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "electric",
    "lat": 36.4801,
    "lng": 127.2892,
    "pay": "180,000원",
    "status": "recruiting",
    "isUrgent": false,
    "workType": "fullDay",
    "workTime": "20:00~04:00",
    "nightWork": true,
    "distanceKm": 4.8,
    "address": "세종 나성동",
    "payTerms": "익일지급",
    "attendanceCount": 5,
    "activeWorkersCount": 2,
    "shortageCount": 1,
    "likeCount": 17,
    "listImage": "https://picsum.photos/seed/ildang-site-13/112/112",
    "date": "2026-05-21",
    "addressDetail": "세종 나성북로 30 상가 4층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 15,
    "title": "월평동 오피스 필름 반일",
    "siteKind": "오피스",
    "trade": "준기공",
    "craft": "film",
    "lat": 36.3582,
    "lng": 127.3641,
    "pay": "95,000원",
    "status": "recruiting",
    "isUrgent": false,
    "workType": "morning",
    "workTime": "08:00~12:30",
    "distanceKm": 1.7,
    "address": "대전 서구 월평동",
    "payTerms": "당일지급",
    "attendanceCount": 3,
    "activeWorkersCount": 1,
    "shortageCount": 1,
    "likeCount": 14,
    "listImage": "https://picsum.photos/seed/ildang-site-15/112/112",
    "date": "2026-05-24",
    "addressDetail": "대전 서구 월평로 120 오피스 6층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 16,
    "title": "둔산동 오피스 필름 보조",
    "siteKind": "오피스",
    "beginnerOk": true,
    "trade": "조공",
    "craft": "film",
    "lat": 36.3542,
    "lng": 127.3798,
    "pay": "110,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "08:00~17:00",
    "distanceKm": 0.6,
    "address": "대전 서구 둔산동",
    "date": "2026-05-20",
    "addressDetail": "대전 서구 둔산대로 88 5층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 17,
    "title": "갈마동 상가 필름 기공",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "film",
    "lat": 36.3468,
    "lng": 127.3712,
    "pay": "220,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "07:30~18:00",
    "distanceKm": 1.1,
    "address": "대전 서구 갈마동",
    "date": "2026-05-21",
    "addressDetail": "대전 서구 갈마중로 33",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 18,
    "title": "선화동 야간 전기 배선",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "electric",
    "lat": 36.3294,
    "lng": 127.3768,
    "pay": "180,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "20:00~04:00",
    "distanceKm": 2.3,
    "address": "대전 중구 선화동",
    "date": "2026-05-20",
    "addressDetail": "대전 중구 선화서로 12",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 19,
    "title": "용운동 아파트 타일 보조",
    "siteKind": "아파트",
    "beginnerOk": true,
    "trade": "조공",
    "craft": "tile",
    "lat": 36.3312,
    "lng": 127.4245,
    "pay": "140,000원",
    "status": "recruiting",
    "workType": "afternoon",
    "workTime": "13:00~18:00",
    "distanceKm": 3.4,
    "address": "대전 동구 용운동",
    "date": "2026-05-22",
    "addressDetail": "대전 동구 용운로 120 102동",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 20,
    "title": "탄방동 상가 철거 보조",
    "siteKind": "상가",
    "trade": "조공",
    "craft": "facility",
    "lat": 36.3489,
    "lng": 127.3846,
    "pay": "95,000원",
    "status": "recruiting",
    "workType": "morning",
    "workTime": "08:00~13:00",
    "distanceKm": 0.8,
    "address": "대전 서구 탄방동",
    "date": "2026-05-21",
    "addressDetail": "대전 서구 탄방로 55 지하1층",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 21,
    "title": "궁동 오피스텔 도배 마감",
    "siteKind": "오피스텔",
    "trade": "기공",
    "craft": "wallpaper",
    "closingSoon": true,
    "lat": 36.3426,
    "lng": 127.3988,
    "pay": "165,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "08:30~17:30",
    "distanceKm": 1.8,
    "address": "대전 유성구 궁동",
    "date": "2026-05-23",
    "addressDetail": "대전 유성구 궁동 410",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 22,
    "title": "대덕구 법동 콘크리트 타설",
    "siteKind": "신축",
    "trade": "기공",
    "craft": "facility",
    "lat": 36.3638,
    "lng": 127.4088,
    "pay": "250,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "06:30~16:00",
    "distanceKm": 2.6,
    "address": "대전 대덕구 법동",
    "date": "2026-05-24",
    "addressDetail": "대전 대덕구 법동 88 현장",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 23,
    "title": "판암동 설비 배관 보조",
    "siteKind": "아파트",
    "trade": "준기공",
    "craft": "facility",
    "lat": 36.3348,
    "lng": 127.4188,
    "pay": "190,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "07:00~16:30",
    "distanceKm": 3.2,
    "address": "대전 동구 판암동",
    "date": "2026-05-25",
    "addressDetail": "대전 동구 판암로 210",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 24,
    "title": "정림동 상가 용접 보강",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "facility",
    "lat": 36.3524,
    "lng": 127.3872,
    "pay": "200,000원",
    "status": "recruiting",
    "isUrgent": true,
    "workType": "fullDay",
    "workTime": "08:00~18:00",
    "distanceKm": 0.5,
    "address": "대전 서구 정림동",
    "date": "2026-05-21",
    "addressDetail": "대전 서구 정림로 44",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 25,
    "title": "부사동 목수 보조",
    "siteKind": "주택",
    "beginnerOk": true,
    "trade": "조공",
    "craft": "facility",
    "lat": 36.3278,
    "lng": 127.3824,
    "pay": "80,000원",
    "status": "recruiting",
    "workType": "morning",
    "workTime": "09:00~14:00",
    "distanceKm": 2.5,
    "address": "대전 중구 부사동",
    "date": "2026-05-20",
    "addressDetail": "대전 중구 계백로 210",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 26,
    "title": "성남동 필름 단기 (만료 테스트)",
    "siteKind": "상가",
    "trade": "조공",
    "craft": "film",
    "lat": 36.3512,
    "lng": 127.3924,
    "pay": "140,000원",
    "status": "recruiting",
    "workType": "afternoon",
    "workTime": "13:00~17:00",
    "distanceKm": 1.2,
    "address": "대전 서구 성남동",
    "date": "2026-05-15",
    "addressDetail": "대전 서구 성남로 12",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 27,
    "title": "둔산동 필름 긴급헬프",
    "siteKind": "상가",
    "trade": "조공",
    "craft": "film",
    "lat": 36.3558,
    "lng": 127.3816,
    "pay": "90,000원",
    "status": "recruiting",
    "isUrgent": true,
    "liveHelp": true,
    "workType": "shortHelp",
    "workTime": "14:00~17:00",
    "helpTime": "오후 2~5시",
    "helpTitle": "필름 보조 급구",
    "helpDescription": "마감 직전 보조 3시간",
    "distanceKm": 0.4,
    "address": "대전 서구 둔산동",
    "date": "2026-05-20",
    "addressDetail": "대전 서구 둔산로 100",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 28,
    "title": "관평동 타일 마감임박",
    "siteKind": "아파트",
    "trade": "기공",
    "craft": "tile",
    "closingSoon": true,
    "lat": 36.3442,
    "lng": 127.4052,
    "pay": "180,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "08:00~17:00",
    "distanceKm": 2,
    "address": "대전 유성구 관평동",
    "date": "2026-05-20",
    "addressDetail": "대전 유성구 관평로 88",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 29,
    "title": "노은동 페인트 초보 가능",
    "siteKind": "아파트",
    "beginnerOk": true,
    "trade": "조공",
    "craft": "paint",
    "lat": 36.3398,
    "lng": 127.3942,
    "pay": "110,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "08:30~17:00",
    "distanceKm": 1.5,
    "address": "대전 유성구 노은동",
    "date": "2026-05-26",
    "addressDetail": "대전 유성구 노은로 55",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 30,
    "title": "세종 고운동 전기 분전함",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "electric",
    "lat": 36.4788,
    "lng": 127.2824,
    "pay": "220,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "08:00~17:00",
    "distanceKm": 5.1,
    "address": "세종 고운동",
    "date": "2026-05-22",
    "addressDetail": "세종 고운동 210",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 31,
    "title": "중촌동 상가 도장",
    "siteKind": "상가",
    "trade": "기공",
    "craft": "paint",
    "lat": 36.3256,
    "lng": 127.3888,
    "pay": "150,000원",
    "status": "recruiting",
    "workType": "fullDay",
    "workTime": "08:00~17:00",
    "distanceKm": 2.7,
    "address": "대전 중구 중촌동",
    "date": "2026-05-17",
    "addressDetail": "대전 중구 중앙로 220",
    "participants": [],
    "briefing": [],
    "alerts": []
  },
  {
    "id": 32,
    "title": "신탄진동 필름 반일",
    "siteKind": "상가",
    "trade": "준기공",
    "craft": "film",
    "lat": 36.3576,
    "lng": 127.3764,
    "pay": "125,000원",
    "status": "recruiting",
    "workType": "morning",
    "workTime": "08:00~12:00",
    "distanceKm": 0.9,
    "address": "대전 서구 신탄진동",
    "date": "2026-05-27",
    "addressDetail": "대전 서구 신탄진로 18",
    "participants": [],
    "briefing": [],
    "alerts": []
  }
];
