import { MAP_ITEM_TYPE } from "../constants/mapItemTypes";

export const LIFE_MAP_MOCK_ITEMS = [
  {
    id: "parking:dunsan-public-1",
    type: MAP_ITEM_TYPE.PARKING,
    title: "둔산 공영주차장",
    address: "대전 서구 둔산동 1420 인근 공영주차장",
    lat: 36.3512,
    lng: 127.3828,
    distanceText: "도보 4분",
    meta: "사다리차 대기 가능 · 현장까지 도보 4분",
    tags: ["공영", "사다리차", "1톤 가능"],
    relatedFieldId: 1,
    relevanceScore: 92,
    scope: "arrival",
    operationPriority: "important",
    experienceTags: ["사다리차 대기 가능", "큰 차 진입 무난"],
    free: true,
    sourceMeta: {
      createdBy: "대전 오야지 인증",
      updatedAt: "2026-05-24",
      trustScore: 86,
      reportCount: 1,
      verificationStatus: "verified",
    },
    price: "30분 600원",
    heightLimit: "2.1m",
    largeVehicleOk: true,
    ladderTruckOk: true,
    comments: ["주차 2대 가능", "오전엔 자리 있음", "대형차 진입 무난"],
  },
  {
    id: "restaurant:dunsan-driver-1",
    type: MAP_ITEM_TYPE.RESTAURANT,
    title: "둔산 기사식당",
    address: "대전 서구 둔산동 1443",
    lat: 36.3496,
    lng: 127.3863,
    distanceText: "도보 5분",
    meta: "새벽 6시부터 · 혼밥 편함",
    tags: ["기사식당", "새벽 가능", "혼밥"],
    relatedFieldId: 1,
    relevanceScore: 58,
    scope: "nearby",
    operationPriority: "optional",
    experienceTags: ["새벽 식사 가능", "혼자 먹기 편함"],
    sourceMeta: {
      createdBy: "현장팀 메모",
      updatedAt: "2026-05-22",
      trustScore: 72,
      reportCount: 0,
      verificationStatus: "recent",
    },
    soloOk: true,
    restaurantType: "기사식당",
    parkingOk: true,
    earlyOpen: true,
    comments: ["점심 빨리 나옴", "작업복 가능", "혼밥 편함"],
  },
  {
    id: "restroom:dunsan-park-1",
    type: MAP_ITEM_TYPE.RESTROOM,
    title: "샘머리공원 화장실",
    address: "대전 서구 둔산동 샘머리공원",
    lat: 36.3508,
    lng: 127.3891,
    distanceText: "도보 6분",
    meta: "오전 작업 전 들르기 좋음",
    tags: ["공공", "상시", "현장 전"],
    relatedFieldId: 1,
    relevanceScore: 46,
    scope: "nearby",
    operationPriority: "optional",
    experienceTags: ["작업 전 들르기 좋음"],
    sourceMeta: {
      createdBy: "현장팀 메모",
      updatedAt: "2026-05-21",
      trustScore: 68,
      reportCount: 0,
      verificationStatus: "recent",
    },
    comments: ["화장실 깨끗함", "오전 작업 전 들르기 좋음"],
  },
  {
    id: "access_info:dunsan-tower-1",
    type: MAP_ITEM_TYPE.ACCESS_INFO,
    title: "둔산 타워 출입",
    address: "대전 서구 둔산동 1457 둔산타워 후문",
    lat: 36.3523,
    lng: 127.3852,
    distanceText: "현장 입구",
    meta: "출입 등록 필요 · 후문 하역장 진입",
    tags: ["출입 등록", "경비실", "후문"],
    relatedFieldId: 1,
    relevanceScore: 98,
    scope: "field",
    operationPriority: "critical",
    experienceTags: ["출입 등록 필요", "경비실 호출"],
    sourceMeta: {
      createdBy: "오야지 인증",
      updatedAt: "2026-05-25",
      trustScore: 94,
      reportCount: 0,
      verificationStatus: "verified",
    },
    entryMethod: "후문 하역장으로 진입 후 경비실 호출",
    elevator: "B1 화물 엘리베이터",
    securityCall: true,
    residentEscortRequired: false,
    comments: ["후문 경비실 호출", "출입 등록 필요"],
  },
  {
    id: "elevator:dunsan-tower-freight-1",
    type: MAP_ITEM_TYPE.ELEVATOR,
    title: "B1 화물 엘리베이터",
    address: "대전 서구 둔산동 1457 둔산타워 B1",
    lat: 36.352,
    lng: 127.3856,
    distanceText: "후문 안쪽",
    meta: "엘베 느림 · 보호재 확인",
    tags: ["화물", "느림", "보호재"],
    relatedFieldId: 1,
    relevanceScore: 90,
    scope: "field",
    operationPriority: "important",
    experienceTags: ["엘베 대기 김", "보호재 확인"],
    sourceMeta: {
      createdBy: "오야지 인증",
      updatedAt: "2026-05-24",
      trustScore: 88,
      reportCount: 1,
      verificationStatus: "verified",
    },
    location: "후문 진입 후 우측 B1",
    useNote: "오전 8시대 대기 길고, 벽면 보호재 확인 필요",
    comments: ["엘베 느림", "보호재 확인 필요"],
  },
  {
    id: "material_pickup:dunsan-warehouse-1",
    type: MAP_ITEM_TYPE.MATERIAL_PICKUP,
    title: "필름 자재 상차 위치",
    address: "대전 서구 둔산동 1457 동측 골목",
    lat: 36.3485,
    lng: 127.3839,
    distanceText: "차량 3분",
    meta: "오전 8시 전 상차 권장",
    tags: ["상차", "자재", "단속 주의"],
    relatedFieldId: 1,
    relevanceScore: 88,
    scope: "arrival",
    operationPriority: "critical",
    experienceTags: ["정차 단속 주의", "8시 전 상차 유리"],
    sourceMeta: {
      createdBy: "자재팀 메모",
      updatedAt: "2026-05-25",
      trustScore: 91,
      reportCount: 2,
      verificationStatus: "verified",
    },
    pickupPoint: "동측 골목 하역 구역",
    warning: "출근 시간대 정차 단속 주의",
    comments: ["오전 8시 전 상차 권장", "정차 단속 주의"],
  },
  {
    id: "site_memo:dunsan-memo-1",
    type: MAP_ITEM_TYPE.SITE_MEMO,
    title: "민원 주의 구간",
    address: "대전 서구 둔산동 1457 주변",
    lat: 36.3501,
    lng: 127.3814,
    distanceText: "현장 주변",
    meta: "오전 소음 민원 잦음",
    tags: ["민원 잦음", "엘베 느림", "동선 주의"],
    relatedFieldId: 1,
    relevanceScore: 86,
    scope: "field",
    operationPriority: "optional",
    experienceTags: ["민원 많음", "자재 이동 동선 주의", "엘베 느림"],
    sourceMeta: {
      createdBy: "현장 경험 메모",
      updatedAt: "2026-05-23",
      trustScore: 82,
      reportCount: 1,
      verificationStatus: "recent",
    },
    memo: "9시 전 절단 작업 피하기",
    warning: "자재 이동 시 엘리베이터 보호재 확인",
    comments: ["오후엔 민원 많음", "자재 동선 조용히 이동"],
  },
  {
    id: "sos:dunsan-help-1",
    type: MAP_ITEM_TYPE.SOS,
    title: "주변 긴급헬프",
    address: "대전 서구 둔산동 1450 인근",
    lat: 36.3531,
    lng: 127.3834,
    distanceText: "차량 2분",
    meta: "전기 보조 1명 급함",
    tags: ["긴급", "주변"],
    relatedFieldId: 1,
    relevanceScore: 62,
    scope: "nearby",
    operationPriority: "critical",
    experienceTags: ["근처 긴급 도움"],
    sourceMeta: {
      createdBy: "긴급헬프",
      updatedAt: "2026-05-25",
      trustScore: 76,
      reportCount: 0,
      verificationStatus: "live",
    },
    status: "긴급 도움 요청",
    need: "전기 보조 1명",
    comments: ["근처 팀 확인 필요"],
  },
  {
    id: "meeting:dunsan-gate-1",
    type: MAP_ITEM_TYPE.MEETING_PLACE,
    title: "둔산 타워 후문 집결",
    address: "대전 서구 둔산동 1457 후문",
    lat: 36.3517,
    lng: 127.3844,
    distanceText: "현장 앞",
    meta: "초행 팀은 후문 편의점 앞에서 만나기",
    tags: ["집결", "후문"],
    relatedFieldId: 1,
    relevanceScore: 74,
    scope: "arrival",
    operationPriority: "important",
    experienceTags: ["초행자 찾기 쉬움", "차량 정차 짧게"],
    sourceMeta: {
      createdBy: "현장팀 메모",
      updatedAt: "2026-05-25",
      trustScore: 80,
      reportCount: 0,
      verificationStatus: "recent",
    },
    comments: ["초행자 찾기 쉬움", "차량 정차는 짧게"],
  },
  {
    id: "hardware:dunsan-tool-1",
    type: MAP_ITEM_TYPE.HARDWARE_STORE,
    title: "둔산 철물",
    address: "대전 서구 둔산동 1438",
    lat: 36.3478,
    lng: 127.3869,
    distanceText: "차량 4분",
    meta: "칼날·테이프 급하게 사기 좋음",
    tags: ["철물", "소모품"],
    relevanceScore: 32,
    scope: "nearby",
    operationPriority: "optional",
    experienceTags: ["소모품 빠르게 해결"],
    sourceMeta: {
      createdBy: "현장팀 메모",
      updatedAt: "2026-05-20",
      trustScore: 65,
      reportCount: 0,
      verificationStatus: "recent",
    },
    comments: ["칼날 급할 때 가까움"],
  },
  {
    id: "convenience:dunsan-store-1",
    type: MAP_ITEM_TYPE.CONVENIENCE_STORE,
    title: "후문 편의점",
    address: "대전 서구 둔산동 1457 후문 앞",
    lat: 36.3516,
    lng: 127.3841,
    distanceText: "도보 2분",
    meta: "아침 물·장갑 사기 좋음",
    tags: ["편의점", "후문"],
    relatedFieldId: 1,
    relevanceScore: 40,
    scope: "nearby",
    operationPriority: "optional",
    experienceTags: ["아침 준비", "만남장소 겸용"],
    sourceMeta: {
      createdBy: "현장팀 메모",
      updatedAt: "2026-05-22",
      trustScore: 70,
      reportCount: 0,
      verificationStatus: "recent",
    },
    comments: ["아침 물 사기 좋음", "만남장소로도 무난"],
  },
];
